apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apiflows.fullname" . }}
  labels:
    app: {{ template "apiflows.name" . }}
type: Opaque
data:
  azure-b2c-tenantname: {{ .Values.azure.b2c.tenantname | b64enc | quote }}
  azure-b2c-tenantid: {{ .Values.azure.b2c.tenantid | b64enc | quote }}
  azure-b2c-clientid: {{ .Values.azure.b2c.clientid | b64enc | quote }}
  azure-b2c-policyname: {{ .Values.azure.b2c.policyname | b64enc | quote }}
  azure-b2c-audience: {{ .Values.azure.b2c.audience | b64enc | quote }}
