apiVersion: v1
kind: Secret
metadata:
  name: {{ template "apiflows.fullname" . }}
  labels:
    app: {{ template "apiflows.name" . }}
type: Opaque
data:
  azure-b2c-tenantname: {{ .Values.azure.b2c.tenantname }}
  azure-b2c-tenantid: {{ .Values.azure.b2c.tenantid }}
  azure-b2c-clientid: {{ .Values.azure.b2c.clientid }}
  azure-b2c-policyname: {{ .Values.azure.b2c.policyname }}
  azure-b2c-audience: {{ .Values.azure.b2c.audience }}
