# Default values for apiflows.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
logLevel : debug

provider: azure

azure:
  aksResourceGroup: aks-non-permanent
  filestoragenrconnexionstring: DefaultEndpointsProtocol=https;AccountName=zmuserstorage2;AccountKey=Ri9buc11+4uMXV8C2cGEQHlSvJ5erCNxw4Tfq6to8LEP6l+qDbZLlUB79OJ0bFwxWZLrLWpSZLS++U+gaBASGw==;EndpointSuffix=core.windows.net
  filestoragedbconnexionstring: DefaultEndpointsProtocol=https;AccountName=zmuserstorage2;AccountKey=Ri9buc11+4uMXV8C2cGEQHlSvJ5erCNxw4Tfq6to8LEP6l+qDbZLlUB79OJ0bFwxWZLrLWpSZLS++U+gaBASGw==;EndpointSuffix=core.windows.net

  b2c:
    tenantname: apiflows
    tenantid: apiflows.onmicrosoft.com
    clientid: 5c6375a2-5df5-4a7f-b1f5-ed3b4accd6b8
    policyname: B2C_1_ROPC
    audience: 5b4c86c8-52c9-4bfd-aa89-7d272dd8fe31

ingressControllerIpAddress: 51.145.39.222
repositoryAddress: zmeter2.azurecr.io
zoneName: apivalley.org
dnsZone: apivalley.org
  #zmeter2.apivalley.org


image:
  repository: zmeter2.azurecr.io/apiflows
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  annotations: { service.beta.kubernetes.io/azure-load-balancer-resource-group: static-ips-permanent}
  type: ClusterIP
  loadBalancerIP: 51.145.13.65
  port: 1337
  nodePort: 30337
  targetPort: 2337

  portHttps: 1338
  nodePortHttps: 30338
  targetPortHttps: 2338

  portAASI: 1437
  nodePortAASI: 30437
  targetPortAASI: 2437
  portAAROPC: 1439
  nodePortAAROPC: 30439
  targetPortAAROPC: 2439

  porthttp: 1339
  targetPorthttp: 2339


ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: [/]
  servicePort: 1337
  resthost: apiflows-rest.apivalley.org
  hosts:
    - apiflows-rest.apivalley.org
  # rest.zmeter2.apivalley.org
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitorEnabled: false


